"""
Sentinel AI — Automated Report Generator
Produces HTML and JSON incident reports for audit and compliance.
"""

import json
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path


class ReportGenerator:
    def __init__(self, data_dir: str = "data"):
        self.data_dir = Path(data_dir)
        self.data_dir.mkdir(exist_ok=True)
        self.incidents_file = self.data_dir / "incidents.json"

    def load_incidents(self) -> list:
        if self.incidents_file.exists():
            return json.loads(self.incidents_file.read_text())
        return []

    def save_incident(self, incident: dict):
        """Append a new incident to persistent storage."""
        incidents = self.load_incidents()
        incidents.append(incident)
        self.incidents_file.write_text(json.dumps(incidents, indent=2))

    def generate_html_report(self, days: int = 7) -> str:
        incidents = self.load_incidents()
        cutoff = datetime.now(timezone.utc) - timedelta(days=days)
        recent = [i for i in incidents if self._after(i.get("timestamp", ""), cutoff)]

        by_risk = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        by_type = {}
        for i in recent:
            risk = i.get("risk", "LOW")
            by_risk[risk] = by_risk.get(risk, 0) + 1
            t = i.get("type", "UNKNOWN")
            by_type[t] = by_type.get(t, 0) + 1

        risk_color = {"CRITICAL": "#dc2626", "HIGH": "#f97316", "MEDIUM": "#d97706", "LOW": "#16a34a"}
        rows = "".join(f"""
        <tr>
          <td style='font-family:monospace;font-size:12px'>{i.get('timestamp','')[:19]}</td>
          <td><span style='background:{risk_color.get(i.get('risk','LOW'), '#888')}22;
              color:{risk_color.get(i.get('risk','LOW'), '#888')};
              padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600'>
              {i.get('risk','LOW')}</span></td>
          <td>{(i.get('type','') or '').replace('_',' ')}</td>
          <td style='font-family:monospace'>{i.get('source_ip','unknown')}</td>
          <td style='font-size:12px;max-width:300px;overflow:hidden;text-overflow:ellipsis'>{i.get('ai_analysis','')[:120]}</td>
        </tr>
        """ for i in sorted(recent, key=lambda x: x.get("timestamp", ""), reverse=True))

        html = f"""
        <!DOCTYPE html><html><head><meta charset="UTF-8">
        <title>Sentinel AI — Security Report</title>
        <style>
          body {{ font-family:system-ui,sans-serif; max-width:1000px; margin:40px auto; padding:0 20px; color:#111; }}
          h1 {{ font-size:24px; margin-bottom:4px; }}
          .meta {{ color:#666; font-size:14px; margin-bottom:32px; }}
          .kpi-grid {{ display:grid; grid-template-columns:repeat(4,1fr); gap:16px; margin-bottom:32px; }}
          .kpi {{ background:#f9f9f9; border:1px solid #e5e5e5; border-radius:8px; padding:20px; text-align:center; }}
          .kpi-value {{ font-size:36px; font-weight:700; line-height:1; }}
          .kpi-label {{ color:#666; font-size:13px; margin-top:4px; }}
          table {{ width:100%; border-collapse:collapse; font-size:13px; }}
          th {{ background:#f4f4f4; padding:10px 12px; text-align:left; border-bottom:2px solid #ddd; }}
          td {{ padding:10px 12px; border-bottom:1px solid #eee; }}
          .footer {{ margin-top:40px; color:#999; font-size:12px; text-align:center; }}
        </style></head><body>
        <h1>🛡️ Sentinel AI — Security Report</h1>
        <div class="meta">Period: Last {days} days &nbsp;•&nbsp; Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</div>
        <div class="kpi-grid">
          <div class="kpi"><div class="kpi-value" style="color:#2563eb">{len(recent)}</div><div class="kpi-label">Total Incidents</div></div>
          <div class="kpi"><div class="kpi-value" style="color:#dc2626">{by_risk['CRITICAL']}</div><div class="kpi-label">Critical</div></div>
          <div class="kpi"><div class="kpi-value" style="color:#f97316">{by_risk['HIGH']}</div><div class="kpi-label">High</div></div>
          <div class="kpi"><div class="kpi-value" style="color:#d97706">{by_risk['MEDIUM']}</div><div class="kpi-label">Medium</div></div>
        </div>
        <h2 style="font-size:16px;margin-bottom:12px">Incident Log</h2>
        <table><thead><tr>
          <th>Timestamp (UTC)</th><th>Risk</th><th>Type</th><th>Source IP</th><th>AI Analysis</th>
        </tr></thead><tbody>{rows if rows else '<tr><td colspan=5 style="text-align:center;color:#999;padding:32px">No incidents in this period</td></tr>'}</tbody></table>
        <div class="footer">Generated by Sentinel AI — github.com/Nasimashaoz/sentinel-ai</div>
        </body></html>
        """
        return html

    def generate_json_report(self, days: int = 7) -> dict:
        incidents = self.load_incidents()
        cutoff = datetime.now(timezone.utc) - timedelta(days=days)
        recent = [i for i in incidents if self._after(i.get("timestamp", ""), cutoff)]
        by_risk = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for i in recent:
            by_risk[i.get("risk", "LOW")] = by_risk.get(i.get("risk", "LOW"), 0) + 1
        return {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "period_days": days,
            "total_incidents": len(recent),
            "by_risk": by_risk,
            "incidents": recent,
        }

    def save_html_report(self, days: int = 7) -> str:
        html = self.generate_html_report(days)
        fname = f"report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M')}.html"
        path = self.data_dir / fname
        path.write_text(html)
        return str(path)

    def _after(self, ts_str: str, cutoff: datetime) -> bool:
        try:
            dt = datetime.fromisoformat(ts_str)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt >= cutoff
        except Exception:
            return False
